# Netlify Configuration
# netlify.toml

[build]
  # Není potřeba build command, máme statický HTML
  publish = "."

# Headers pro bezpečnost a výkon
[[headers]]
  for = "/*"
  [headers.values]
    # Bezpečnostní hlavičky
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/index.html"
  [headers.values]
    # HTML se nemá cachovat
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirecty (pokud potřebujete)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/kalkulacka"
  to = "/#calculator"
  status = 301

# 404 stránka
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Funkce (pokud budete chtít přidat)
[functions]
  directory = "functions"

# Formuláře
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Environment variables příklad
# V Netlify UI nastavte:
# GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"