Netlify Configuration for Hypotéka AI
This file configures the build, functions, and redirects.

[build]
We are deploying a static site, so we just need to publish the root directory.

publish = "."

[functions]
Specifies the directory where Netlify will find the serverless functions.

directory = "functions/"
This is the correct rule for a Single Page Application (SPA).
It rewrites all paths to index.html with a 200 status, allowing client-side routing.

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
Security and caching headers for all assets.

[[headers]]
for = "/*"
[headers.values]
# Security headers
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache assets for 1 hour in the browser.
Cache-Control = "public, max-age=3600"

Specific headers for the main HTML file to prevent caching.

[[headers]]
for = "/index.html"
[headers.values]
# Do not cache the HTML file to ensure users always get the latest version.
Cache-Control = "no-cache, no-store, must-revalidate"