# Konfigurace pro build a nasazení na Netlify v5.1
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  publish = "."
  port = 8888

[build.environment]
  NODE_VERSION = "18"

# Přesměrování pro jednodušší volání API z frontendu
# /api/chat -> /.netlify/functions/chat
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Bezpečnostní hlavičky
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    # Opravená a funkční Content-Security-Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:;"

