# Konfigurace pro build a nasazení na Netlify
[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Nastavení pro lokální vývojový server (netlify dev)
[dev]
  framework = "#static"
  publish = "."
  port = 8888

# Definice proměnných prostředí
[build.environment]
  NODE_VERSION = "18"

# Hlavičky pro zvýšení bezpečnosti
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # OPRAVENÁ Content Security Policy
    # Povoluje skripty z cdn.tailwindcss.com a cdn.jsdelivr.net (pro Chart.js)
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://generativelanguage.googleapis.com; img-src 'self' data:;"

# Pravidla pro cachování statických souborů
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

