# Netlify Configuration - v6.0 - Final

[build]
  # Directory with the serverless functions.
  functions = "netlify/functions"
  # The directory to publish, which is the root in this case.
  publish = "."

# Production environment settings
[build.environment]
  NODE_VERSION = "18"

# Serverless function configuration
[functions]
  node_bundler = "esbuild"

# This rule proxies requests from your site to the corresponding Netlify function.
# This avoids CORS issues and hides the .netlify/functions path from the user.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security and caching headers for the site.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    # Basic Content Security Policy. Allows scripts from self, TailwindCSS, and Chart.js.
    # Allows API calls to self (Netlify functions via /api/ path).
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self';"

