[build]
  # Build settings
  publish = "."
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect rules for SPA behavior
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Form handling
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Error pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  # Directory for serverless functions
  directory = "netlify/functions/"
  
  # Individual function settings
  [functions.gemini]
    # Timeout for AI function (max 10 seconds for Netlify)
    timeout = 10